environment: prod
serviceAccount: spark-operator-spark
envVars:
  DEBUG_SPARK_CONFIG: 0
javaOptions: "-Dconfig.resource=application.prod.conf -DLogLevel=WARN"
driver:
  cores: 3
  memory: "12g"
executor:
  instances: 3
  cores: 4
  memory: "12g"
hostNetwork: false
imagePullPolicy: IfNotPresent
userId: 0
