name: 'Manual: Start Release'

on:
  workflow_dispatch:

jobs:
  prepare-release:
    name: Prepare release
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.type.outputs.branch }}
      modules: ${{ steps.vars.outputs.modules }}
      version: ${{ steps.vars.outputs.version }}
      reg_owner:  ${{ steps.vars.outputs.reg_owner }}
      pr_url: ${{ steps.pr.outputs.pr_url }}

    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/hotfix'

    steps:
      - name: Set release type
        id: type
        run: |
          if [ "$REF" == "refs/heads/main" ]
          then
              echo "::set-output name=branch::release"
          else
              echo "::set-output name=branch::hotfix"
          fi
        env:
          REF: ${{ github.ref }}

      - name: Delete current release branch
        uses: dawidd6/action-delete-branch@v3
        if: steps.type.outputs.branch == 'release'
        continue-on-error: true
        with:
          github_token: ${{github.token}}
          branches: release

      - name: Create new release branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        if: steps.type.outputs.branch == 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: release

      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.type.outputs.branch }}
          fetch-depth: 0

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v10

      - name: Cache sbt
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
          key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

      - name: Bump Release
        if: steps.type.outputs.branch == 'release'
        shell: bash
        run: make bump-release-and-push

      - name: Bump Hotfix
        if: steps.type.outputs.branch == 'hotfix'
        shell: bash
        run: make bump-patch-and-push

      - name: Set variables
        id: vars
        env:
          REGISTRY_OWNER: ${{ github.repository_owner }}
        run: |
          make version
          echo ::set-output name=version::$(make version)
          echo ::set-output name=reg_owner::$(echo "$REGISTRY_OWNER" | tr '[:upper:]' '[:lower:]')
          echo ::set-output name=modules::$(make list-modules-json)

      - name: Find old PR
        uses: juliangruber/find-pull-request-action@v1
        id: find-pull-request
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.type.outputs.branch }}

      - name: Close old PR
        if: ${{ steps.find-pull-request.outputs.number > 0 }}
        uses: peter-evans/close-pull@v1
        with:
          pull-request-number: ${{ steps.find-pull-request.outputs.number }}
          comment: Auto-closing pull request
          delete-branch: false

      - name: Create new PR
        id: pr
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ steps.type.outputs.branch }}
          destination_branch: main
          pr_title: "Release ${{ steps.vars.outputs.version }} to PROD"
          pr_body: ":gear: *Automated PR*\nWhen merged ${{ github.event.repository.name }} ${{ steps.vars.outputs.version }} ${{ steps.type.outputs.branch }} will be released to PROD\nClose PR to cancel"
          pr_reviewer: "${{ github.actor }}"
          pr_assignee: "${{ github.actor }}"
          pr_label: "auto-pr,release"
          pr_allow_empty: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Show Output
        shell: bash
        run: |
          echo "modules: ${{ steps.vars.outputs.modules }}"
          echo "version: ${{ steps.vars.outputs.version }}"
          echo "pr_url: ${{ steps.pr.outputs.pr_url }}"

      - name: Slack on error
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          username: 'github actions'
          author_name: ''
          icon_emoji: ':github:'
          text: ":x: The workflow `${{ github.workflow }}` triggered by `${{ github.event_name }}` failed\n\n:arrow_right: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|See Log>"
          status: ${{ job.status }}
          fields: repo,message,commit,workflow
        if: ${{ failure() }}

  build-deploy:
    name: Build & Deploy Release
    runs-on: ubuntu-latest
    needs: prepare-release
    strategy:
      matrix:
        module: ${{fromJson(needs.prepare-release.outputs.modules)}}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: ${{ needs.prepare-release.outputs.branch }}
          fetch-depth: 0

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v10

      - name: Cache sbt
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
          key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

      - name: Container Registry Login
        shell: bash
        env:
          REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          REGISTRY_USERNAME: ${{ github.actor }}
        run: make registry-docker-push-login

      - name: Dockerize
        shell: bash
        run: make docker-build ${{ matrix.module }}

      - name: Publish Docker Image to Github Container Registry
        shell: bash
        env:
          REGISTRY_OWNER: ${{ needs.prepare-release.outputs.reg_owner }}
        run: make docker-push-registry ${{ matrix.module }}

      - name: Install Helm
        shell: bash
        run: make install-helm

      - name: Github Container Registry Helm Login
        shell: bash
        run: make registry-helm-push-login
        env:
          CHART_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          CHART_USERNAME: ${{ github.actor }}

      - name: Append Environmental Values to Chart Values
        shell: bash
        env:
          ENVIRONMENT: test
        run: make helm-concat ${{ matrix.module }}

      - name: Push Charts to Github Helm Repo
        shell: bash
        env:
          ENVIRONMENT: test
          CHART_OWNER: ${{ needs.prepare-release.outputs.reg_owner }}
        run: make helm-push-registry ${{ matrix.module }}

      - name: Slack on error
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          username: 'github actions'
          author_name: ''
          icon_emoji: ':github:'
          text: ":x: The workflow `${{ github.workflow }} (${{ matrix.module }})` triggered by `${{ github.event_name }}` failed\n\n:arrow_right: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|See Log>"
          status: ${{ job.status }}
          fields: repo,message,commit,workflow
        if: ${{ failure() }}


  success:
    needs: [ prepare-release, build-deploy ]
    name: Notify success
    runs-on: ubuntu-latest

    steps:
      - name: Deploy notification
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          username: 'github actions'
          author_name: ''
          icon_emoji: ':github:'
          status: ${{ job.status }}
          fields:
          text: ":rocket: ${{ github.event.repository.name }} *v${{ needs.prepare-release.outputs.version }}* deployed to *TEST*\n\n:arrow_right: <${{ needs.prepare-release.outputs.pr_url}}|Release To PROD>"

